# GitHub Sponsors
github: [milos85vasic]

# Open Collective
open_collective: shareconnect

# Ko-fi
ko_fi: shareconnect

# Patreon
patreon: shareconnect

# Custom sponsorship URLs
custom: ['https://shareconnect.dev/sponsor', 'https://www.paypal.me/shareconnect']